#!/usr/bin/env bash
# I don't know what this script does yet

function func1 () {
    res=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $res" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]
then
    func1 "$1" "$2"
elif [ "$#" -eq 1 ]
then
    func1 "$1" "www"
    func1 "$1" "lb-01"
    func1 "$1" "web-01"
    func1 "$1" "web-02"
fi
