#!/usr/bin/env bash
# Bash script to configure Nginx server

apt-get update
apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" >  /var/www/html/index.html

service nginx restart
