#!/usr/bin/env bash
# Bash Script to Configure Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" >  /var/www/html/index.html

new_string="\tserver_name _;\n\trewrite ^\/redirect_me fast.com permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

service nginx restart
