#!/usr/bin/env bash
# A bash script

touch /var/run/myscript.pid
pgrep -f 100-process_and_pid_file > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	trap "rm -f /var/run/myscript.pid | echo I hate the kill command; exit" SIGTERM SIGQUIT
	trap "echo Y U no love me?!; exit" SIGINT
done
