#!/usr/bin/env bash
# A bash script to manage another bash script

if [[ $1 == 'start' ]]
then
	sudo ./manage_my_process &
	pgrep -f manage_my_process >> /var/run/my_process.pid
	echo "manage_my_process started"

elif [[ $1 == 'stop' ]]
then
	pkill -f manage_my_process
	sudo rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [[ $1 == 'restart' ]]
then
	pkill -f manage_my_process
	sudo rm -f /var/run/my_process.pid
	sudo ./manage_my_process &
        pgrep -f manage_my_process >> /var/run/my_process.pid
        echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
