#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#+ but "Hi" on the 9th iteration
i=0
while [ $i -lt 10 ]
do
	if [ $i == 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
