#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#+ but "bad luck" or "good luck" on 4th or 8th iteration
i=0
while [ $i -lt 10 ]
do
	if [ $i == 3 ]; then
		echo "bad luck"
	elif [ $i == 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
