#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2\tlocalhost" >> ~/hosts.new
echo -e "8.8.8.8\t\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
