#!/usr/bin/env bash
# Run Apache on the holbertonschool/265-0 Docker container.

apt-get update
apt -y install apache2
touch index.html
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
