#!/usr/bin/env bash
# Run Apache on the holbertonschool/265-0 Docker container.

apt-get update
apt-get -y install apache2
touch /var/www/html/index.html
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 restart
