#!/usr/bin/env bash
# Script to correct nginx config

sudo service apache2 stop
sudo pkill apache2

sudo sed -i '1s/^/listen 8080 default_server;\n/' /etc/nginx/nginx.conf
sudo sed -i '1s/^/user nginx;\n/' /etc/nginx/nginx.conf
sudo service nginx restart
